project_identifier_env: CROWDIN_PROJECT
api_key_env: CROWDIN_API_KEY
base_path: ./locale/docs/

files:
  - source: 'en/LC_MESSAGES/*.po'
    translation: '%locale_with_underscore%/LC_MESSAGES/%original_file_name%'
    languages_mapping:
      locale_with_underscore:
        ar: ar
        es: es
        hi: hi
